//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurant.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillInfor
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> BillID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
