//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurant.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.BillInfors = new HashSet<BillInfor>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<System.DateTime> DateCheckIn { get; set; }
        public Nullable<System.DateTime> DateCheckOut { get; set; }
        public string Status { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillInfor> BillInfors { get; set; }
        public virtual Table Table { get; set; }
    }
}
