//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurant.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDestails = new HashSet<OrderDestail>();
        }
    
        public int ID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Quantily { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDestail> OrderDestails { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
