//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurant.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDestail
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Destail { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<double> UnitPrice { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
